import time
import random
from docuflow.utils import get_logger

class LLMService:
    def __init__(self, model_name: str = "gemini-1.5-pro", fail_rate: float = 0.0):
        self.logger = get_logger(__name__)
        self.model_name = model_name
        self.fail_rate = fail_rate
        
        # Telemetry metrics stored on the instance for extraction
        self.last_input_tokens = 0
        self.last_output_tokens = 0
        self.last_cost_usd = 0.0

    def generate(self, prompt: str) -> str:
        """Simulate LLM text generation with latency, token usage, and cost logs."""
        if random.random() < self.fail_rate:
            # Simulate a rate limit or timeout exception
            raise RuntimeError("LLM Service Error: Rate limit exceeded or API timeout.")

        # Simulate processing delay
        time.sleep(random.uniform(0.1, 0.3))

        # Approximate token counts (4 chars per token)
        self.last_input_tokens = max(1, len(prompt) // 4)
        
        # Determine prompt type to generate appropriate mock answers
        prompt_lower = prompt.lower()
        if "summarize" in prompt_lower:
            response = "This is a concise summary of the provided text chunk, highlighting the main points."
        elif "questions" in prompt_lower:
            response = '["What is the main topic of the text?", "How does this process work?", "Why is this important?"]'
        elif "faithfulness" in prompt_lower or "eval" in prompt_lower or "validate" in prompt_lower:
            response = "yes"
        else:
            response = "This is a detailed mock answer generated by the LLM response engine to address the user query based on the retrieved context."

        self.last_output_tokens = max(1, len(response) // 4)
        
        # Cost mapping
        self.last_cost_usd = (self.last_input_tokens * 1.5e-6) + (self.last_output_tokens * 2.0e-6)
        
        return response
