import random
import time
from typing import Optional

from openai import OpenAI

from docuflow.configs import settings
from docuflow.utils import get_logger


class LLMService:
    def __init__(
        self,
        model_name: Optional[str] = None,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        mock: bool = False,
        fail_rate: float = 0.0,
    ):
        self.logger = get_logger(__name__)
        self.mock = mock
        self.fail_rate = fail_rate

        # Config fallback
        self.model_name = model_name or settings.LLM_MODEL
        self.api_key = api_key or settings.GROQ_API_KEY
        self.base_url = base_url or settings.LLM_BASE_URL

        # Telemetry metrics stored on the instance for extraction
        self.last_input_tokens = 0
        self.last_output_tokens = 0
        self.last_cost_usd = 0.0

        # Initialize live client if not in mock mode
        if not self.mock:
            if not self.api_key:
                self.logger.warning("No API Key configured for LLMService. Falling back to mock mode.")
                self.mock = True
            else:
                self.client = OpenAI(
                    api_key=self.api_key,
                    base_url=self.base_url,
                )

    def generate(self, prompt: str) -> str:
        """Generate response text with telemetry (tokens, cost, latency)."""
        if self.mock:
            return self._generate_mock(prompt)

        # Live integration
        if random.random() < self.fail_rate:
            raise RuntimeError("LLM Service Error: Simulated rate limit exceeded or API timeout.")

        self.logger.info(f"Sending live completion request to model: {self.model_name}")
        start_time = time.perf_counter()
        try:
            response = self.client.chat.completions.create(
                model=self.model_name, messages=[{"role": "user", "content": prompt}]
            )
            latency_ms = (time.perf_counter() - start_time) * 1000

            # Telemetry
            self.last_input_tokens = response.usage.prompt_tokens
            self.last_output_tokens = response.usage.completion_tokens

            # Groq Llama 3.3 70b pricing: $0.15 / M input tokens, $0.60 / M output tokens
            if "llama-3.3-70b" in self.model_name.lower():
                self.last_cost_usd = (self.last_input_tokens * 0.15e-6) + (self.last_output_tokens * 0.60e-6)
            else:
                self.last_cost_usd = (self.last_input_tokens * 1.5e-6) + (self.last_output_tokens * 2.0e-6)

            self.logger.debug(
                f"Live LLM call succeeded in {latency_ms:.2f}ms. "
                f"Tokens: in={self.last_input_tokens}, out={self.last_output_tokens}, cost=${self.last_cost_usd:.6f}"
            )
            return response.choices[0].message.content

        except Exception as e:
            self.logger.error(f"Live LLM request failed: {e}", exc_info=True)
            raise RuntimeError(f"LLM API request failed: {e}")

    def _generate_mock(self, prompt: str) -> str:
        """Simulate LLM text generation with latency, token usage, and cost logs."""
        if random.random() < self.fail_rate:
            raise RuntimeError("LLM Service Error: Rate limit exceeded or API timeout.")

        # Simulate processing delay
        time.sleep(random.uniform(0.1, 0.3))

        # Approximate token counts (4 chars per token)
        self.last_input_tokens = max(1, len(prompt) // 4)

        # Determine prompt type to generate appropriate mock answers
        prompt_lower = prompt.lower()
        if "summarize" in prompt_lower:
            response = "This is a concise summary of the provided text chunk, highlighting the main points."
        elif "questions" in prompt_lower:
            response = (
                '["What is the main topic of the text?", "How does this process work?", "Why is this important?"]'
            )
        elif "faithfulness" in prompt_lower or "eval" in prompt_lower or "validate" in prompt_lower:
            response = "yes"
        else:
            response = "This is a detailed mock answer generated by the LLM response engine to address the user query based on the retrieved context."

        self.last_output_tokens = max(1, len(response) // 4)

        # Cost mapping (simulation values)
        self.last_cost_usd = (self.last_input_tokens * 1.5e-6) + (self.last_output_tokens * 2.0e-6)

        return response
